### ISSUE TITLE
✨ Add License Middleware

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [sageteamorg/django-sage-tools#20]
#### Description

We need to implement middleware that verifies a valid license key for accessing the Django application. This middleware will ensure that only users with a valid license can access the application, enhancing security and compliance with licensing agreements.

#### Requirements

1. **Middleware Functionality:**
   - Create a middleware class `LicenseMiddleware` that will check each request for a valid license key.
   - Support specifying the license key via settings.
   - Provide clear HTTP responses when access is denied due to an invalid or missing license key.

2. **Integration:**
   - Ensure compatibility with existing authentication and permission systems.

#### Acceptance Criteria

- The middleware should be easy to configure and integrate with existing Django settings.
- It should verify the presence and validity of a license key.
- Access should be restricted based on the validity of the license key, and appropriate HTTP responses should be returned.

**Comment by sepehr-akbarzadeh** [comment]
Explain it more. i didn't get the idea exactly.

what you mean License? License for whom? or source code?

**Comment by ARYAN-NIKNEZHAD** [comment]
Hi @sepehr-akbarzadeh this is the overview
# Overview
The middleware we're implementing is designed to ensure that only users with a valid license key can access the Django application. This license key acts as a security measure to restrict access to authorized users only.

# What is a License Key?
A license key in this context is a unique code provided to users who have permission to use the application. It's similar to a product key you might use to activate a piece of software. This key can be used to:

- **Control Access**: Only users with a valid license key can use the application.
- **Ensure Compliance**: It ensures that the application is being used in accordance with licensing agreements, such as subscription models or trial periods.

# Purpose of the Middleware
The middleware acts as a gatekeeper. When a request is made to the Django application, the middleware will:

- **Check for a License Key**: Look for a license key in the request (e.g., in headers).
- **Validate the License Key**: Compare the provided key against a valid key stored in the application settings.
- **Allow or Deny Access**: If the key is valid, the request proceeds to the application. If not, the middleware returns an appropriate HTTP response (e.g., 403 Forbidden).

# Steps and Functionality
1. **Create Middleware Class**: Define a class `LicenseMiddleware` that will handle the license key check.
2. **Specify License Key in Settings**: Allow the license key to be configured via Django settings for easy management.
3. **HTTP Responses**: Return clear and appropriate responses when access is denied due to an invalid or missing license key (e.g., 403 Forbidden with a message explaining the issue).

# Integration and Compatibility
The middleware should seamlessly integrate with existing Django settings and work alongside the existing authentication and permission systems. It should be straightforward to configure and not interfere with other aspects of the application.
